#!/bin/bash

# one argument: the directory of a wp-config.php file
domain=$1
filename=$2

if [ -z "$1" ]; then
echo "Error: Missing argument 1 - Domain to be backed up"
exit
fi

if [ -z "$2" ]; then
echo "Error: Missing argument 2 - Backup name"
exit
fi

thedir=/var/www/vhosts/$1/

if [ ! -d "$thedir" ]; then
echo "Error: '$thedir' not found."
exit
fi

if [ -d "$thedir/httpdocs/" ]; then
thedir=/var/www/vhosts/$1/httpdocs/
fi

if [ ! -d "./backups/$filename" ]; then
mkdir ./backups/$filename
fi

zip -r ./backups/$filename/httpdocs.zip $thedir